version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # RabbitMQ Management UI
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - chat-network

  chat-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chat-app
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_URL=${RABBITMQ_URL}
    volumes:
      - ./web/templates:/app/web/templates
    networks:
      - chat-network
    env_file:
      - .env

networks:
  chat-network:
    driver: bridge

volumes:
  rabbitmq_data:
